### ISSUE TITLE
Need written justification to use Monix

### ISSUE THREAD

**Issue by JohnReedLOL** [monix/monix#734] opened 2018-10-05 04:36 UTC
Sorry to bother you,

I am working on a Scala project and I would like to be able to use Monix. That being said, the bank I work at has a lot of red tape and they don't approve anything unless you convince them to do so. In about a month I'm going to do a demo of the open source libraries that I want them to put into their system. To help me get approval, could you write something explaining that they won't have any issues with copyright or patents and that this library is being actively maintained, is well documented, and has real world business value?

**Comment by ngbinh** [comment] 2018-10-05 05:34
I think all of the answers to your questions are available right here in the repo.

**Comment by JohnReedLOL** [comment] 2018-10-05 23:11
Banks tend to be more risk averse than startups and tech companies.

**Comment by Avasil** [comment] 2018-10-06 08:00
Well, regarding copyright it's [Apache License](https://github.com/monix/monix/blob/master/LICENSE.txt) so see if it works for your Bank

It is being actively maintained, it was a bit slower due to `Cats-Effect` development recently but `3.0.0` release is coming and you can see it in activity around pull requests. 

It's also quite mature because `2.x` is used in production in many companies ( I don't have a list but there are e.g. Zalando, Samsung Research, we might want to reactivate [this issue](https://github.com/monix/monix/issues/233) to get more confirmed companies).

For documentation, see [monix.io](https://monix.io/docs/3x/) which is admittedly lacking at times but some parts are really good and we already have few quite big documentation PRs ready so it's going to be only better. At least I know it's going to be my focus right after release.

On the other hand, [Scaladocs in the codebase](https://github.com/monix/monix/blob/master/monix-eval/shared/src/main/scala/monix/eval/Task.scala) / [API](https://monix.io/api/3.0/) are IMO top notch. We also do our best to help on gitter channel in case of any questions.

For business value, apart from anything you get from pure FP you also get a lot of tools for writing asynchronous programs. Performance aside, very rich API and "composability" should help your Bank expressing its requirements in simpler and more correct/robust way. Note that you don't have to go full on pure FP if your Bank doesn't want to do this. Monix works very well for mixed codebases and that's important to us.

If you use `3.0.x` then you also get everything from `Cats-Effect` and seamless interop with other libraries in ecosystem (mainly http4s, doobie, fs2). 

Take a look at [docs](https://monix.io/docs/3x/) to see what's inside and presentations for handy examples:

https://monix.io/presentations/

and 

https://www.youtube.com/watch?v=brnq6RsVeN4

I won't write sales pitch for you because I'm not a good "marketing person" and you know your Company better but I can help you find good arguments so ask here if you need more.

Good luck and thanks for considering Monix!

**Comment by alexandru** [comment] 2018-11-15 15:05
Will close this for now. Feel free to add more comments or to re-open it if it's the case.

**Closed by alexandru** 2018-11-15 15:05 UTC
