### ISSUE TITLE
Support for dynamically scoped variables

### ISSUE THREAD

**Issue by missingfaktor** [monix/monix#246] opened 2016-10-15 01:26 UTC
This is a feature request for support for dynamically scoped variables in Monix.

The standard library implementation of dynamically scoped variables – [`DynamicVariable`](http://www.scala-lang.org/api/2.11.8/#scala.util.DynamicVariable) – uses `ThreadLocal` variables. This is not safe to use in code using `Task`s, since the computations along the chain could be dispatched on different threads. It would be useful to have a `DynamicVariable` implementation that works with Monix `Task`s. 

Here is how a typical use may look like:

``` scala
// Assume all of the following three live in three different classes.

val currentRequestContext = new MonixDynamicVariable[AwesomeAppRequestContext]

...

def foo(request: Request) = {
  val requestId = generateRequestIdForEndToEndTracking(request)
  val requestContext = buildRequestContext(request, requestId)
  currentRequestContext.withValue(requestContext) {
    bar(request.someParam)
  }
}

...

def bar(param: Param) = {
  doStuff()
  someLogger.debug("Beginning stuff", requestId = currentRequestContext.get.requestId)
  returnSomeOtherStuff()
}

```

In absence of such a construct, users are burdened with having to pass this parameter explicitly down the stack. The situation could be improved slightly by passing it as an `implicit` argument or including a `Reader` in your effect stack, but both approaches bring in their own tediousness. `DynamicVariable` is potentially a cleaner and more lightweight approach than the two.

Here is an implementation for Twitter/Finagle futures – [Local](https://github.com/twitter/util/blob/develop/util-core/src/main/scala/com/twitter/util/Local.scala) – for a reference.

**Comment by fwbrasil** [comment] 2016-10-15 05:29
Locals would make monix very appealing, especially because it already supports cancellation if I understood it correctly. To be honest, it's hard to imagine how I'd implement more complex systems without these features.

Note that the local works with Twitter Futures because `Local.Context` is propagated by the future implementation ([example](https://github.com/twitter/util/blob/develop/util-core/src/main/scala/com/twitter/util/Promise.scala)).

**Comment by alexandru** [comment] 2016-10-17 07:18
Hi guys, 

`Local` sounds cool and I'd like us to have it in Monix. But off the top of my head, here are some concerns:

One thing to consider is that it will be error prone, no matter what we do, because automatic propagation of the local context relies on detecting asynchronous boundaries and that's not feasible. And it's not `Task` that can handle it, but rather the `Scheduler`, because `Task.Async` instances can execute arbitrary user code and so in the task implementation we aren't able to tell when that context should be saved and restored. 

A better idea here is to have the `Scheduler` handling this save/restore, because it's in a better position to detect asynchronous boundaries.

Also this local context propagation will imply at least a `ThreadLocal` read, on every runnable being executed, which isn't cheap and if benchmarking shows that it is a problem, then we'll have to make this context propagation optional and disabled by default (to be enabled through the `ExecutionModel`).

**Comment by alexandru** [comment] 2016-10-17 07:31
Some more thoughts:

Pushing this implementation in the `Scheduler` will mean that not all schedulers will be capable of it, because we cannot force it through the base `Scheduler` interface, as it already does too much.  It's only OK if we can have special schedulers that can handle it, but leave the option open for scheduler implementations that don't. This is a net negative. However on the positive side, having this in the `Scheduler` means that it can work not only for `Task`, but also for Scala's `Future`.

On the other hand, in writing my message above, I forgot that in PR #240 that I'm preparing we already have a way to detect asynchronous boundaries in Tasks that could be used for saving and restoring the local context.

Btw, I'm traveling with business somewhere in Germany, so my online connectivity is limited. Will think more about this.

**Comment by alexandru** [comment] 2016-11-03 08:48
I'm assigning this to the 2.2.0 milestone - we need 2.1.0 out first, as it changes how async tasks get evaluated.

**Comment by benjumanji** [comment] 2017-08-02 13:44
This feature is very interesting / important to me, I would love to take a crack on it with some guidance. I am very familiar with how this stuff works in twitter land, less so with monix, but the principles should mostly be the same, I assume.

I would like to use to be able to properly propagate the active span from opentracing.io / custom per request logging context, that kind of thing.

**Comment by alexandru** [comment] 2017-08-04 11:39
@benjumanji I still haven't investigated how this feature could be implemented.

If you want to take a crack at it, that's fine, however I have reservations, because it has to have good performance and has to be safe, or otherwise it has to be opt-in and safe. We already have a mechanism for adding "execution options" to a Task, and so we could have `task.executeWithOptions(_.enableDynamicVars)`. But I'm not sure how feasible that is to implement an opt-in.

In the implementation itself, I'm guessing you need to transport these vars over async boundaries.
One place to do that would be here: https://github.com/monix/monix/blob/master/monix-eval/shared/src/main/scala/monix/eval/internal/TaskRunLoop.scala#L143

So if you want to try out an implementation, I would be happy to provide guidance.

**Comment by alexandru** [comment] 2017-08-04 11:55
No, had a benchmarks sub-project, but it was badly maintained so I deleted it.

If you want you can implement it gradually. Start with something that works first.

**Comment by benjumanji** [comment] 2017-08-04 12:00
> Start with something that works first.

This is normally a good place to start. You just have mentioned performance a lot in this thread, I assumed there would be tracking. I'll worry about fast once I have correct. Thanks!

**Comment by alexandru** [comment] 2017-08-09 16:45
@benjumanji I just re-added a `benchmarks` sub-project in https://github.com/monix/monix/pull/409, going forward we're going to use it to guard against regressions, most importantly in this case being the performance of `Task.flatMap`.

**Comment by leandrob13** [comment] 2017-08-30 16:11
I share the same interest as @benjumanji and I would like to start some work on this matter. As you guys pointed out I will get something that works first and then iterate on improvements. Is that ok  @alexandru ?

**Comment by alexandru** [comment] 2017-08-30 16:29
@leandrob13 go for it, feel free to ask for pointers as well.

**Comment by alexandru** [comment] 2017-08-30 16:30
@benjumanji have you had any progress?

**Comment by leandrob13** [comment] 2017-08-30 16:33
@alexandru thanks, I will!

**Closed** 2017-11-13 21:44 UTC
Labels: enhancement

**Comment by alexandru** [comment] 2017-11-13 22:00
For completeness, we now have on master:

- `monix.execution.schedulers.TracingScheduler` - that can wrap schedulers into an implementation that can transport locals over async boundaries
- `monix.execution.misc.Local` (the equivalent of `com.twitter.util.Local`, with some slight differences in the type of the context)
- `monix.eval.TaskLocal`, the pure variant meant to work with `Task`
- the `Task` implementation itself, which can transport locals over async boundaries

So there are two ways of doing this, depending on context. In the context of `Task`, it now has the option of transporting those locals in its implementation. For everything else (e.g. `Future`), where needed, there's the `TracingScheduler`. The `Task` implementation does not need `TracingScheduler` within its own context, as it manages its own run-loop.
