### ISSUE TITLE
Zipping two Observables of different sizes yields non-deterministic result.

### ISSUE THREAD

**Issue by wjlow** [monix/monix#1167] opened 2020-04-27 04:44 UTC
## Versions
JDK: 11
Monix: 3.1.0
Scala: 2.13.1
SBT: 1.3.10

## How to reproduce

```
    val task = Observable(1, 2, 3).zip(Observable(Observable(1, 2, 3), Observable.raiseError(new RuntimeException("This should not be zipped"))).concat).completedL
    // Run it 50 times
    Task.traverse(Range(0, 50).toList)(_ => task).map(_ => ExitCode.Success)
```

The first `Observable` contains 3 values, the second `Observable` contains 4 values (the last value is an error).

When zipped, I expect the error to be left out, because there is no value for it to be paired with. However, when I run this many times, it eventually fails with an exception `RuntimeException("This should not be zipped")`, which indicates that `zip` isn't dropping that value.

Changing the second `Observable` to `Observable(1,2,3,4)` results in a program that occasionally does not terminate. I suspect these are moments when it would've thrown an exception in the original case.

I recently raised an issue related to zipping a prepended `Observable`, I don't know if they're related: https://github.com/monix/monix/issues/1164

**Comment by Avasil** [comment] 2020-04-27 06:41
Thanks for the detailed report! I have a feeling it is related, it seems like sometimes it skips one of the values but I haven't had time yet to figure it out

**Comment by wjlow** [comment] 2020-04-27 06:44
I'm curious what the expected behaviour is for that snippet of code. I guess occasionally the second stream (the one with the error) completes before the first stream, hence the observed error? If that's the case, the non-determinism is potentially not a bug, and just my misunderstanding.

However, changing the second stream to `Observable(1,2,3,4)` does occasionally result in a program that does not terminate. That feels like incorrect behaviour to me.

Just for clarity, I mean this piece of code:

```
    val task = Observable(1, 2, 3).zip(Observable(1, 2, 3, 4).completedL
    // Run it 50 times
    Task.traverse(Range(0, 50).toList)(_ => task).map(_ => ExitCode.Success)
```

**Comment by alexandru** [comment] 2020-04-27 10:10
>  `val task = Observable(1, 2, 3).zip(Observable(Observable(1, 2, 3), Observable.raiseError(new RuntimeException("This should not be zipped"))).concat).completedL`

Note that the final `raiseError` does not count as an "element". This is because, due to the protocol, the final `onComplete` and `onError` message isn't back-pressured.

So the error gets transmitted downstream, depending on whether or not the final `onComplete` (of the `zip`) was sent or not.

**Comment by alexandru** [comment] 2020-04-27 10:12
What I mean is, in the presence of a `raiseError`, you shouldn't expect deterministic results, because thrown errors lead to non-determinism, unless you catch and handle them somehow.

**Comment by alexandru** [comment] 2020-04-27 10:13
> Changing the second Observable to Observable(1,2,3,4) results in a program that occasionally does not terminate. I suspect these are moments when it would've thrown an exception in the original case.

Well, this shouldn't happen.

Some code for reproducing this behavior would be appreciated.

**Comment by alexandru** [comment] 2020-04-27 13:02
We have to investigate the claim above. Marking as #bug.

**Comment by wjlow** [comment] 2020-04-27 23:57
Thanks @alexandru 

I've got code in this repo that reproduces the non-terminating behaviour of zipping two Observables of differing sizes.

https://github.com/wjlow/monix-non-terminating

**Closed** 2020-06-04 09:42 UTC
Labels: bug
