### ISSUE TITLE
Observable recovery does not work

### ISSUE THREAD

**Issue by gabor-aranyossy** [monix/monix#380] opened 2017-07-01 19:40 UTC
After playing around with the reactive extensions I noticed a weird behaviour when trying to recover an exploding `Observable`. Instead of calling the recovery code it stops the stream and calls the `Scheduler`'s `reportFailure`. My interpretation might by wrong, but [this](https://github.com/gabor-aranyossy/monix/commit/d84884e9c11d7c5084b8266f03e98ddd12745f79) I think should work.

My expectation was that this works the same way as [scalaz-stream](https://github.com/scalaz/scalaz-stream) and other similar libraries.

**Comment by alexandru** [comment] 2017-07-28 13:26
@gabor-aranyossy throwing exceptions is problematic and sometimes we can't recover, or to be more precise, we can only recover in case the final `onComplete` event wasn't sent already.

However if an onComplete already happened, then we can no longer signal a subsequent onError event, because that would break the contract, so the only thing we can do is to log it somewhere. And sometimes the behavior is undefined.

Note that Scalaz-stream uses a different communication protocol so in the presence of exceptions it will break in different ways.

Please paste a code sample, so that I can help.

Note that I remember answering this on the Gitter channel. If it wasn't you, then sorry for the delay, it's summer time, vacations, etc 😁

**Comment by gabor-aranyossy** [comment] 2017-07-30 10:10
No problem for the delay. :) Here is the code I was testing with: [ErrorHandling.scala](https://gist.github.com/gabor-aranyossy/dc8205044e990e832a2c2651ab1a3487)

I was using "io.monix" %% "monix" % "2.3.0"

**Comment by alexandru** [comment] 2018-11-15 13:50
This is no longer reproducible on `master`. I think it's fixed in #473.

**Closed by alexandru** 2018-11-15 13:50 UTC

**Comment by gabor-aranyossy** [comment] 2018-11-16 07:52
thanks for the fix! 👍
