### ISSUE TITLE
Publish for Scala 2.13.0-M5?

### ISSUE THREAD

**Issue by SethTisue** [monix/monix#786] opened 2018-11-29 01:09 UTC
has anyone looked at this? perhaps all of monix's dependencies are now available for M5?

in the 2.13 community build, all of monix's dependencies is green, so that provides some evidence that this might be ready to work on

**Comment by SethTisue** [comment] 2018-12-05 23:14
@alexandru fyi I'll be on vacation Dec 8–Jan 2, anything here I can help with before then?

**Comment by alexandru** [comment] 2018-12-06 07:10
We released Cats-Effect. I'm working on it. Thanks for letting me know, will try a release either today or tomorrow.

**Comment by SethTisue** [comment] 2018-12-06 20:42
> We released Cats-Effect

awesome! scala/make-release-notes@3da410a4ad03e6a9924b5eb277474250611db1e2

**Comment by NeQuissimus** [comment] 2019-01-30 14:31
Looks like publishing to 2.13.0-M5 is a bit of an undertaking :)

You'll see lots of these:
`overriding method nonEmpty in trait IterableOnceOps is deprecated (since 2.13.0): nonEmpty is defined as !isEmpty; override isEmpty instead`

and 

```
[error] /home/nequi/dev/monix/monix-execution/shared/src/main/scala/monix/execution/misc/test/TestInlineMacros.scala:22:36: Unused import
[error] import scala.language.experimental.macros
```

I was going to give this a shot but I am afraid I don't have enough spare time atm :(

**Comment by guymers** [comment] 2019-02-03 12:18
Hey @SethTisue, is the change in behaviour of `Future.successful(5).foreach(_ => throw new RuntimeException("blah"))` in 2.13 expected? (see https://github.com/monix/monix/pull/823 for context)

**Comment by SethTisue** [comment] 2019-02-03 15:31
@guymers hey @viktorklang?

**Comment by viktorklang** [comment] 2019-02-03 21:00
@SethTisue @guymers The observed change in behavior is due to the fact that the new implementation does not refer to the EC beyond submission to it—so there's nowhere to report the failure. However, since it is documented as:

" *  Since this method executes asynchronously and does not produce a return value,
 *  any non-fatal exceptions thrown will be reported to the `ExecutionContext`."

I think this is actually a regression and should be fixed.
I'll investigate how that can be addressed without impacting performance/memory consumption negatively.

**Comment by viktorklang** [comment] 2019-02-04 15:54
@SethTisue I've addressed, and fixed the regression tests, in my PR here: https://github.com/scala/scala/pull/7663/files#diff-e0c06059ba197fea5927c4e4b0f3d837R469

**Comment by alexandru** [comment] 2019-02-05 09:35
Sorry for the delay guys, I've been overwhelmed with other engagements. I'm also blocked on releasing a new release candidate on features that I want to get in and for which I haven't had the proper time or focus.

@SethTisue would publishing a hash version suffice?

**Comment by SethTisue** [comment] 2019-02-05 15:55
> @SethTisue would publishing a hash version suffice?

sure, any kind of artifact people can do testing with. (ideally cross-published for 2.11 and 2.12, though people can also put conditionals in their builds)

**Comment by alexandru** [comment] 2019-02-05 15:58
We've got a PR for fixing the deprecations in progress, at #823, will publish a version as soon as that one is merged.

**Comment by guymers** [comment] 2019-02-11 11:18
Hey @viktorklang , [monix.reactive.SerializableSuite](https://github.com/monix/monix/blob/7cf74a9238a69e85991471130a453fed7ef31d24/monix-reactive/jvm/src/test/scala/monix/reactive/SerializableSuite.scala#L59) is failing on 2.13 due to a `Future` from a `Promise` no longer able to be serialised. Is this an expected change of behaviour?

```
Welcome to Scala 2.12.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_202).
Type in expressions for evaluation. Or try :help.

scala> import java.io.{ByteArrayOutputStream, ObjectOutputStream}
import java.io.{ByteArrayOutputStream, ObjectOutputStream}

scala> :paste
// Entering paste mode (ctrl-D to finish)

def serialize(obj: Serializable) = {
  val bytes = new ByteArrayOutputStream()
  val out = new ObjectOutputStream(bytes)
  out.writeObject(obj)
  out.flush()
  out.close()
  bytes.toByteArray
}

// Exiting paste mode, now interpreting.

serialize: (obj: Serializable)Array[Byte]

scala> import scala.concurrent._
import scala.concurrent._

scala> trait Blah extends Serializable { def future: Future[String] }
defined trait Blah

scala> val p = Promise[String]()
p: scala.concurrent.Promise[String] = Future(<not completed>)

scala> val b = new Blah { val future = p.future }
b: Blah{val future: scala.concurrent.Future[String]} = $anon$1@50a6fbd5

scala> serialize(b)
res0: Array[Byte] = Array(-84, ...
```

```
Welcome to Scala 2.13.0-M5 (OpenJDK 64-Bit Server VM, Java 1.8.0_202).
Type in expressions for evaluation. Or try :help.

scala> import java.io.{ByteArrayOutputStream, ObjectOutputStream}
import java.io.{ByteArrayOutputStream, ObjectOutputStream}

scala> :paste
// Entering paste mode (ctrl-D to finish)

def serialize(obj: Serializable) = {
  val bytes = new ByteArrayOutputStream()
  val out = new ObjectOutputStream(bytes)
  out.writeObject(obj)
  out.flush()
  out.close()
  bytes.toByteArray
}

// Exiting paste mode, now interpreting.

serialize: (obj: Serializable)Array[Byte]

scala> import scala.concurrent._
import scala.concurrent._

scala> trait Blah extends Serializable { def future: Future[String] }
defined trait Blah

scala> val p = Promise[String]()
p: scala.concurrent.Promise[String] = Future(<not completed>)

scala> val b = new Blah { val future = p.future }
b: Blah{val future: scala.concurrent.Future[String]} = $anon$1@33667238

scala> serialize(b)
java.io.NotSerializableException: scala.concurrent.Future$InternalCallbackExecutor$
  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
  at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
  at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
  at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
  at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
  at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
  at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
  at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
  at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
  at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
  at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
  at .serialize(<pastie>:4)
  ... 38 elided
```

**Comment by viktorklang** [comment] 2019-02-11 11:56
Hi @guymers,

Scala Future / Promise have never been intended to be serializable—it is also unclear what that would mean. What would the expected semantics be?

**Comment by alexandru** [comment] 2019-02-11 13:06
@viktorklang it wasn't intended to be serializable, but it was and in Scala 2.13 it isn't anymore. Any specific reason for why not?

This isn't a problem for Monix btw, it's just that we have a serialization test that is hitting a `Future` reference.

The folks that ask for everything to be serializable are the folks using Spark 🤷‍♂️ so if something is no longer serializable, it needs to have good, preferably documented reasons for why.

**Comment by alexandru** [comment] 2019-02-11 13:29
@viktorklang and btw, I would love your thoughts on what should or shouldn't be serializable 🙂

**Comment by viktorklang** [comment] 2019-02-11 13:52
@alexandru It "was" serializable in 2.12 but only by accident. Given that Java Serialization is an attack vector my recommendation would be to avoid relying on it at all. (It's also a heavyweight binary format, slow to store and load, etc)

I'm curious as to what semantics would be intended for serializing a Future. I could mark some of the fields as @-transient but deserializing the future would mean that it will never be completed since if it wasn't completed before serialization it won't have anything which completes it anymore.

**Comment by viktorklang** [comment] 2019-02-11 14:02
@alexandru I've marked Promise.Transformation's value, transformation and EC @transient now.

**Comment by viktorklang** [comment] 2019-02-11 15:23
@alexandru track commit here: https://github.com/scala/scala/pull/7663/commits/5cf0d1626725391754bbb0d2480a0b5e0b1d7985

**Comment by SethTisue** [comment] 2019-02-11 22:54
@alexandru GitHub closed this ticket because #823 merged, but I think the ticket should be reopened until you've actually published artifacts for 2.13.0-M5

**Comment by Avasil** [comment] 2019-02-12 08:24
And seems like CI fails exactly because of missing artifacts

**Comment by alexandru** [comment] 2019-02-12 09:39
@SethTisue indeed, I've reopened the issue.

@Avasil unfortunately we left the Mima checks on for 2.13.0-M5, but no previous artifacts are available; I'm disabling it: https://github.com/monix/monix/pull/833

@viktorklang serializing a `Future` is problematic for the reasons you mention, but serializing a `Promise` should be OK. Thanks for marking those fields as being transient.

**Comment by viktorklang** [comment] 2019-02-12 14:37
@alexandru I've reflected a bit on this and I am probably going to revert the @transient additions. It doesn't make sense to serialize a Promise because it's Future could already have callbacks/transformations added to it—in which case what would happen to them? Having a serialization solution which assumes that a Promise is serializable is going to lead to runtime issues.
Therefor it is probably much better for it to fail early rather than lead to hard-to-diagnose issues at runtime. Makes sense?

**Comment by alexandru** [comment] 2019-02-12 14:48
@viktorklang makes sense, if you want to make Promise non-serializable, better to do it now

**Comment by viktorklang** [comment] 2019-02-12 15:19
@alexandru Done: https://github.com/scala/scala/pull/7663/commits/909d125a821bc8dc4e8efaa3715420db59f2f5a6

**Comment by Avasil** [comment] 2019-05-16 10:36
We'll have `2.13-RC1` soon

**Closed by Avasil** 2019-05-16 10:36 UTC
