### ISSUE TITLE
Memory leak with TrampolineExecutionContext$JVMOptimalTrampoline

### ISSUE THREAD

**Issue by mdedetrich** [monix/monix#870] opened 2019-04-25 16:59 UTC
We are currently experience a memory leak when using Monix Task 3.0.0-RC2. The application is mainly using `Task`, along with functions like `delayExecution`/`fromFuture`/`executeAsync` (along with using the default `Scheduler.global`)

Originally we thought it was coming from Doobie, but we narrowed this down to Monix Task. The leak appears to be happening at `monix.execution.schedulers.TrampolineExecutionContext$JVMOptimalTrampoline$$anon$3`. Here is a screenshot of VisualVM showing what the leak looks like

![2019-04-25-185654_1920x1015_scrot](https://user-images.githubusercontent.com/2337269/56753948-09435200-678c-11e9-8a25-9a785d0d4f23.png)

We have around 160k of these instances after running a few hours in production. Not sure if this is related to https://github.com/monix/monix/issues/791 since we are not using `Observable`.

Unfortunately this is company code however I will try and minimize the example

**Comment by mdedetrich** [comment] 2019-04-26 08:40
So I did a bit more digging and I believe its the actual `ThreadLocal` which is where the leak is happening, the `JVMOptimalTrampoline` is setting a `localContext` (which is a `ThreadLocal` that is causing the leak), will investigate further.

**Comment by mdedetrich** [comment] 2019-04-26 09:10
I am also thinking that this may be due to the fact that we are using `Doobie`, which as of latest version provides its own 2 custom `ExecutionContext`'s which seems to be filling up the leak, will try and provide a minimal example.

**Comment by Avasil** [comment] 2019-07-04 06:09
Just linking to the report in doobie: https://github.com/tpolecat/doobie/issues/934

**Comment by sirmax** [comment] 2019-07-16 10:36
I have recently analysed a heap dump of our app where we got ~5M instances of `JVMOptimalTrampoline` yielding (together with related stuff) about 1GB memleak.

In our case it was caused by a misuse of `Scheduler`s – we spawned them in an ad-hoc manner, wrapping plain old `ExecutionContext`s in a small piece of code where we had to run `Task`s to get `Future`s.

As a result, each `Scheduler` had its own `TrampolineExecutionContext` which brought its own _non-static_ `val trampoline: ThreadLocal[Trampoline]` instance. Each of these `ThreadLocal`s were strong reachable for some time, heavily polluting `ThreadLocalMap`s in affected threads.

I don't yet have any suggestions on how (and if) this can be fixed on Monix side, but I think users should be warned against using `Scheduler`s as lightweight throwaway `ExecutionContext` wrappers.

**Comment by mdedetrich** [comment] 2019-07-16 12:36
@sirmax Is this actually a leak or by saying "strong reachable for some time" do you mean that it just took a while for the GC to kick in.

**Comment by mdedetrich** [comment] 2019-07-17 12:04
Okay so I deployed this fix (where we made on the fly `Scheduler` however we are still getting a memory leak although this one seems related to Doobie.

There were also some projects where we did do `Scheduler(ec)` on the fly however there was no memory leak there (and these projects were running for months) so it appears to be a bit more complex.

**Comment by alexandru** [comment] 2019-07-28 07:53
As an update, I'm also investigating the issue.

@mdedetrich if I publish a hash version, would you be willing to try it out?

**Comment by Avasil** [comment] 2019-07-28 08:07
@alexandru

There is a project that demonstrates a link: https://github.com/tpolecat/doobie/issues/934

**Comment by alexandru** [comment] 2019-07-28 19:19
@Avasil thanks, that's useful.

**Comment by alexandru** [comment] 2019-07-28 20:18
@Avasil @mdedetrich I don't think that particular leak is from Monix though — I've just played with the project locally and here's what I get:

![image](https://user-images.githubusercontent.com/11753/62012341-c085a580-b18d-11e9-8fc6-6c73984235e9.png)

From here it seems a lot of `cats.effect.IO.bracket` operations are somehow scheduled for execution on that thread pool.

**Comment by alexandru** [comment] 2019-07-28 20:24
@sirmax any updates?

> I have recently analysed a heap dump of our app where we got ~5M instances of JVMOptimalTrampoline yielding (together with related stuff) about 1GB memleak.

I don't understand how you can have 5 millions of instances of `JVMOptimalTrampoline` without also having 5 millions of threads active. `JVMOptimalTrampoline` is kept in a `ThreadLocal` attached to `Scheduler` instances. So the instances created should be one per thread.

@sirmax can you help us with some profiling?

**Comment by alexandru** [comment] 2019-07-28 20:26
@sirmax sorry, I actually re-read your message. You were creating a lot of `Scheduler` instances. The issue makes sense.

And indeed, `Schedulers` are not throw-aways.

**Comment by mdedetrich** [comment] 2019-07-29 09:35
@alexandru My latest hunch was that the leak was due to doobie (we are actually in the process of migrating our apps to quill). I went over all of our projects at work to make sure that we only use one global instance of `Scheduler` per app and it didn't fix anything from my end (i.e. Doobie still appears to be leaking)

**Comment by oleg-py** [comment] 2019-10-23 08:37
Got this one too.
![leak](https://user-images.githubusercontent.com/4143670/67372807-27490e00-f587-11e9-814e-93e6e9e26fab.PNG)
quill+http4s+monix (No doobie, no cats IO) running on OpenJDK 1.8.0_222

2 thread pools - `Scheduler.traced` and one `Scheduler.fixedPool` which I forgot to wrap in `TracingScheduler`.

**Comment by oleg-py** [comment] 2019-10-23 08:55
It seems that using ThreadLocal in a class instance of BatchingScheduler is the root of the problem. According to some sources, while the ThreadLocal instance can be GC'd, the _value associated with it will leak_ if you don't clear it manually. [This is most recent article I've found, describing pretty much same problem](https://codar.club/blogs/what-your-threadlocal-memory-leak.html).

Since we helpfully do "oh, you have local context propagation, but your scheduler is not a TracingScheduler, let's wrap it" (TS extends BatchingScheduler, which has this ThreadLocal), we create these leaks. The solution would probably be to have this ThreadLocal on a companion and pass `ExecutionContext` manually to methods on `Trampoline`.

@alexandru any opinions on that?

**Comment by Avasil** [comment] 2019-10-23 09:03
@oleg-py 
I think it can be easily reproducible with https://github.com/monix/monix/issues/1033#issuecomment-540149552

Looks like very similar issue. I was trying to solve it a month ago but temporarily gave up

**Comment by oleg-py** [comment] 2019-10-23 09:38
Here's a smaller reproduction for the leak:
```scala
import monix.execution.schedulers.{TestScheduler, TrampolinedRunnable}


object Leak extends App {
  val tr = new TrampolinedRunnable {
    override def run(): Unit = ()
  }
  while (true) {
    val tc = TestScheduler()
    tc.execute(tr)
  }
}
```

**Comment by sirmax** [comment] 2019-10-23 09:54
@oleg-py you don't do `tc.tick()` in your test, is it intentional? Does the problem reproduce on global scheduler?

**Comment by sirmax** [comment] 2019-10-23 09:55
Oh, wait, you create schedulers in a loop! That's a no-no :)

**Comment by mdedetrich** [comment] 2019-10-23 09:56
FYI, in the original project where we found this leak was abandoned because we decided to recode the project using task + quill rather task + doobie (for some reason the task + quill combo is not replicating this).

This is a theoretical suspicion, but it appears that the leak happens in programs that use cats-effect rather than ones that hardcode against a specific effect type (in this case quill-monix)

**Comment by oleg-py** [comment] 2019-10-23 10:15
@sirmax it's just undesirable to throw schedulers away. It's usually grossly inefficient to do it if you are allocating JVM threads, but they should be GCd eventually.

Specifically, `TestScheduler` doesn't create any threads and is actually meant to be "throwaway" for tests (and I don't need `tick` to trigger the leak). But also, any decorators that delegate to an already allocated pool should be 100% okay to throw away, and GC should be able to take care of them easily. The bug here is that it doesn't, due to how ThreadLocal interacts with GC.

@mdedetrich I had this on task + quill-monix setup. I was using `Runner.using(Scheduler.fixedPool(...))` sized against hikari pool to have separate threads for blocking, and since quill-monix uses `localContextPropagation`, we'd be decorating that `fixedPool` in a `TracingScheduler` quite frequently, causing the leak.

I don't know whether doobie is leak-proof, but we definitely have one there, and your original screenshot looks like it's the same issue (tons of trampolines, tons of `ThreadLocalMap.Entry`).

**Comment by sirmax** [comment] 2019-10-23 10:21
@oleg-py the problem here is not in a number of threads but specifically in a number of schedulers. Each scheduler creates its own, _non-static_, `ThreadLocal` (see `TrampolineExecutionContext.trampoline`).

**Comment by oleg-py** [comment] 2019-10-23 10:22
Yes, and since ThreadLocal values leak, this is a bug/gotcha that we have to remove.

**Comment by mdedetrich** [comment] 2019-10-23 10:39
@oleg-py I actually couldn't replicate my problem using (now an old) version of Monix + quill, you can see the repo here along with instructions on how to replicate https://github.com/mdedetrich/task-doobie-memory-leak

Basically doobie + task leaked however quill + monix did not (in as much of an apples to apples comparison that I could make)

**Comment by oleg-py** [comment] 2019-10-25 11:53
@mdedetrich the leak is there when you use `.executeWithOptions(_.enableLocalContextPropagation)`, which e.g. quill `transaction` does under the covers.

I haven't looked into why the doobie leak happens, it might have a different root cause than your production issue. Your screenshot in OP definitely has the symptoms of what I've found, but the one Alex posted from your tests doesn't.

**Closed** 2019-11-07 17:29 UTC
Labels: bug
