### ISSUE TITLE
Task.fromFuture does not support .onErrorRestart

### ISSUE THREAD

**Issue by Naturlih** [monix/monix#608] opened 2018-03-09 08:03 UTC
Following code does not work as expected:
```
object MonixTest {
  import monix.eval.Task
  import scala.concurrent.{Await, Future}
  import scala.concurrent.duration._

  def main(args: Array[String]): Unit = {
    import monix.execution.Scheduler.Implicits.global
    
    val fut = Task.fromFuture(Future {
      println("Hello, world!")
      
      throw new RuntimeException
    })
      .onErrorRestart(2)
      .runAsync

    Await.result(fut, 1.minute)
  }
}
```
, as it's expected to have 3 "Hello, world!" in console, but only one is shown.
The problem is that future is passed by-value, and `.fromFuture` method has no clue how to create new future to do retry.

The quick fix we use at the moment is (note that `future` parameter is passed by-name, not by-value):
```
def fromFuture[T](future: => Future[T]): Task[T] = Task.unit.flatMap(_ => Task.fromFuture(future))
```

**Comment by alexandru** [comment] 2018-03-09 08:18
@Naturlih that is by design.

Use [Task.deferFuture](https://monix.io/api/2.3/monix/eval/Task$.html#deferFuture[A](fa:=%3Escala.concurrent.Future[A]):monix.eval.Task[A]) or [Task.deferFutureAction](https://monix.io/api/2.3/monix/eval/Task$.html#deferFutureAction[A](f:monix.execution.Scheduler=%3Escala.concurrent.Future[A]):monix.eval.Task[A]).

**Comment by alexandru** [comment] 2018-03-14 12:29
@Naturlih will close this issue to keep the issue tracker clean 🙂 but you can reopen it if you think it's necessary.

**Closed by alexandru** 2018-03-14 12:29 UTC
