### ISSUE TITLE
Spurious test failure in CharsReaderObservableSuite

### ISSUE THREAD

**Issue by alexandru** [monix/monix#1169] opened 2020-04-27 12:35 UTC
https://api.travis-ci.org/v3/job/680030361/log.txt

```
[info] monix.reactive.internal.builders.CharsReaderObservableSuite
[info] - fromCharsReaderUnsafe yields a single subscriber observable
[info] - fromCharsReaderUnsafe works for BatchedExecution
[info] - fromCharsReaderUnsafe works for AlwaysAsyncExecution
[info] - fromCharsReaderUnsafe works for SynchronousExecution
[info] - fromCharsReader closes the file handle onComplete
[info] - fromCharsReader closes the file handle onError on first call
[info] - fromCharsReader closes the file handle onError on second call
[info] - fromCharsReader closes the file handle on cancel *** FAILED ***
[info]   received Some(Success(())) != expected None (CharsReaderObservableSuite.scala:181)
[info]     minitest.api.Asserts.assertEquals(Asserts.scala:71)
[info]     minitest.api.Asserts.assertEquals$(Asserts.scala:65)
[info]     monix.reactive.internal.builders.CharsReaderObservableSuite$.assertEquals(CharsReaderObservableSuite.scala:36)
[info]     monix.reactive.internal.builders.CharsReaderObservableSuite$.$anonfun$new$35(CharsReaderObservableSuite.scala:181)
[info]     minitest.SimpleTestSuite.$anonfun$test$1(SimpleTestSuite.scala:27)
[info]     minitest.api.TestSpec$.$anonfun$sync$2(TestSpec.scala:51)
[info]     scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1$$anon$2.block(ExecutionContextImpl.scala:59)
[info]     java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3313)
[info]     scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1.blockOn(ExecutionContextImpl.scala:70)
[info]     scala.concurrent.BatchingExecutor$AsyncBatch.blockOn(BatchingExecutor.scala:202)
[info]     scala.concurrent.package$.blocking(package.scala:124)
[info]     minitest.api.TestSpec$.$anonfun$sync$1(TestSpec.scala:51)
[info]     minitest.api.TestSpec.apply(TestSpec.scala:27)
[info]     minitest.api.Properties.$anonfun$iterator$2(Properties.scala:38)
[info]     minitest.api.TestSpec.apply(TestSpec.scala:27)
[info]     minitest.runner.Task.loop$1(Task.scala:56)
[info]     minitest.runner.Task.$anonfun$execute$1(Task.scala:63)
[info]     scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
[info]     scala.concurrent.BatchingExecutor$AbstractBatch.runN(BatchingExecutor.scala:134)
[info]     scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:163)
```

**Comment by Avasil** [comment] 2020-04-27 15:03
Duplicate of #1030

**Closed by Avasil** 2020-04-27 15:03 UTC
Labels: bug
