### ISSUE TITLE
Task.fromTry type constructor is being eagerly executed

### ISSUE THREAD

**Issue by jupco** [monix/monix#688] opened 2018-07-20 19:20 UTC
I have observed a weird behavior in the `Task.fromTry` function, when I had a  `Try` block which contained a long-time blocking call to a Java library.
What I could see was that my thread was blocked and `timeout` had no effect on this; while reviewing the code I found that this is the contract of `fromTry`
```scala
def fromTry[A](a: Try[A]): Task[A]
```
it receives an evaluated Try so no timeout can be applied because it's already a `Now` or an `Error` but it takes all the time needed to resolve the `Try`

**Comment by alexandru** [comment] 2018-07-23 06:41
`Task.fromTry` being eager is by design. Like many such functions being described in Monix, or in Typelevel Cats in general, strictness is the default and not laziness.

If you want lazy evaluation, you have to mark it as being lazy via one of Task's operators that deal with *suspending side effects*:

- `Task.eval` (also aliased to `delay` from [Cats-Effect](http://typelevel.org/cats-effect/))
- `Task.suspend`

If you're not doing that then the computation is considered *pure* and thus can be eagerly evaluated. Or in other words `Task.fromTry` expects a pure value. So the normal workflow is actually something like this:

```scala
Task.suspend {
  Task.fromTry(Try { 
    f() 
  })
}
```

You don't even need to do that of course, as you can just leave `Task` to catch the exception. But OK, in case you've got some function around that returns `Try`, you can just `suspend` that `fromTry`.

**Comment by alexandru** [comment] 2018-09-02 21:09
Closing as per #689.

**Closed by alexandru** 2018-09-02 21:09 UTC
